# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\python\search_tools\search_tools\search.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_allsearch(object):
    def setupUi(self, allsearch):
        allsearch.setObjectName("allsearch")
        allsearch.resize(889, 808)
        allsearch.setAutoFillBackground(False)
        allsearch.setStyleSheet("")
        allsearch.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(allsearch)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_search_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_search_pushButton.setStyleSheet("\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(208, 208, 208);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(147, 147, 147);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.start_search_pushButton.setObjectName("start_search_pushButton")
        self.horizontalLayout.addWidget(self.start_search_pushButton)
        self.start_keywords_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.start_keywords_lineEdit.setStyleSheet("QLineEdit{\n"
"\n"
"border:1px solid gray;\n"
"\n"
"width:300px;\n"
"\n"
"border-radius:10px;\n"
"\n"
"padding:2px 4px;}")
        self.start_keywords_lineEdit.setText("")
        self.start_keywords_lineEdit.setObjectName("start_keywords_lineEdit")
        self.horizontalLayout.addWidget(self.start_keywords_lineEdit)
        self.proxy_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.proxy_checkBox.setObjectName("proxy_checkBox")
        self.horizontalLayout.addWidget(self.proxy_checkBox)
        self.start_time_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.start_time_spinBox.setMinimum(1)
        self.start_time_spinBox.setMaximum(365)
        self.start_time_spinBox.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.start_time_spinBox.setProperty("value", 365)
        self.start_time_spinBox.setObjectName("start_time_spinBox")
        self.horizontalLayout.addWidget(self.start_time_spinBox)
        self.proxy_test_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.proxy_test_pushButton.setObjectName("proxy_test_pushButton")
        self.horizontalLayout.addWidget(self.proxy_test_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.notice_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.notice_groupBox.setMaximumSize(QtCore.QSize(210, 16777215))
        self.notice_groupBox.setObjectName("notice_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.notice_groupBox)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.notice_output_textBrowser = QtWidgets.QTextBrowser(self.notice_groupBox)
        self.notice_output_textBrowser.setMinimumSize(QtCore.QSize(192, 149))
        self.notice_output_textBrowser.setMaximumSize(QtCore.QSize(192, 144))
        self.notice_output_textBrowser.setStyleSheet("background-color: paleteGreen;\n"
"border-radius:15px")
        self.notice_output_textBrowser.setTabStopWidth(42)
        self.notice_output_textBrowser.setObjectName("notice_output_textBrowser")
        self.verticalLayout.addWidget(self.notice_output_textBrowser)
        self.label = QtWidgets.QLabel(self.notice_groupBox)
        self.label.setStyleSheet("border:none;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.proxy_output_textBrowser = QtWidgets.QTextBrowser(self.notice_groupBox)
        self.proxy_output_textBrowser.setMinimumSize(QtCore.QSize(192, 149))
        self.proxy_output_textBrowser.setMaximumSize(QtCore.QSize(192, 144))
        self.proxy_output_textBrowser.setStyleSheet("background-color: paleteGreen;\n"
"border-radius:15px")
        self.proxy_output_textBrowser.setObjectName("proxy_output_textBrowser")
        self.verticalLayout.addWidget(self.proxy_output_textBrowser)
        self.count_label = QtWidgets.QLabel(self.notice_groupBox)
        self.count_label.setObjectName("count_label")
        self.verticalLayout.addWidget(self.count_label)
        self.count_output_textBrowser = QtWidgets.QTextBrowser(self.notice_groupBox)
        self.count_output_textBrowser.setMinimumSize(QtCore.QSize(192, 156))
        self.count_output_textBrowser.setMaximumSize(QtCore.QSize(192, 16777215))
        self.count_output_textBrowser.setStyleSheet("background-color: paleteGreen;\n"
"border-radius:15px")
        self.count_output_textBrowser.setObjectName("count_output_textBrowser")
        self.verticalLayout.addWidget(self.count_output_textBrowser)
        self.verticalLayout_11.addWidget(self.notice_groupBox)
        self.gridLayout_2.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.final_result_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.final_result_groupBox.setStyleSheet("")
        self.final_result_groupBox.setObjectName("final_result_groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.final_result_groupBox)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.final_result_search_output_textBrowser = QtWidgets.QTextBrowser(self.final_result_groupBox)
        self.final_result_search_output_textBrowser.setMinimumSize(QtCore.QSize(447, 353))
        self.final_result_search_output_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.final_result_search_output_textBrowser.setStyleSheet("background-color: paleteGreen;\n"
"border-radius:15px")
        self.final_result_search_output_textBrowser.setOpenExternalLinks(True)
        self.final_result_search_output_textBrowser.setObjectName("final_result_search_output_textBrowser")
        self.horizontalLayout_2.addWidget(self.final_result_search_output_textBrowser)
        self.gridLayout.addWidget(self.final_result_groupBox, 0, 0, 3, 2)
        self.fofa_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.fofa_groupBox.setObjectName("fofa_groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fofa_groupBox)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fofa_search_output_textBrowser = QtWidgets.QTextBrowser(self.fofa_groupBox)
        self.fofa_search_output_textBrowser.setMinimumSize(QtCore.QSize(190, 158))
        self.fofa_search_output_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fofa_search_output_textBrowser.setStyleSheet("background-color: paleteGreen;\n"
"border-radius:15px")
        self.fofa_search_output_textBrowser.setOpenExternalLinks(True)
        self.fofa_search_output_textBrowser.setObjectName("fofa_search_output_textBrowser")
        self.verticalLayout_5.addWidget(self.fofa_search_output_textBrowser)
        self.gridLayout.addWidget(self.fofa_groupBox, 0, 2, 1, 1)
        self.zoomeye_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.zoomeye_groupBox.setObjectName("zoomeye_groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.zoomeye_groupBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.zoomeye_search_output_textBrowser = QtWidgets.QTextBrowser(self.zoomeye_groupBox)
        self.zoomeye_search_output_textBrowser.setMinimumSize(QtCore.QSize(190, 158))
        self.zoomeye_search_output_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.zoomeye_search_output_textBrowser.setStyleSheet("background-color: paleteGreen;\n"
"border-radius:15px")
        self.zoomeye_search_output_textBrowser.setOpenExternalLinks(True)
        self.zoomeye_search_output_textBrowser.setObjectName("zoomeye_search_output_textBrowser")
        self.verticalLayout_4.addWidget(self.zoomeye_search_output_textBrowser)
        self.gridLayout.addWidget(self.zoomeye_groupBox, 1, 2, 1, 1)
        self.quake_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.quake_groupBox.setObjectName("quake_groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.quake_groupBox)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.quake_search_output_textBrowser = QtWidgets.QTextBrowser(self.quake_groupBox)
        self.quake_search_output_textBrowser.setMinimumSize(QtCore.QSize(190, 158))
        self.quake_search_output_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.quake_search_output_textBrowser.setStyleSheet("background-color: paleteGreen;\n"
"border-radius:15px")
        self.quake_search_output_textBrowser.setOpenExternalLinks(True)
        self.quake_search_output_textBrowser.setObjectName("quake_search_output_textBrowser")
        self.verticalLayout_3.addWidget(self.quake_search_output_textBrowser)
        self.gridLayout.addWidget(self.quake_groupBox, 2, 2, 1, 1)
        self.shodan_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.shodan_groupBox.setObjectName("shodan_groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.shodan_groupBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.shodan_search_output_textBrowser = QtWidgets.QTextBrowser(self.shodan_groupBox)
        self.shodan_search_output_textBrowser.setMinimumSize(QtCore.QSize(167, 158))
        self.shodan_search_output_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.shodan_search_output_textBrowser.setStyleSheet("background-color: paleteGreen;\n"
"border-radius:15px")
        self.shodan_search_output_textBrowser.setOpenExternalLinks(True)
        self.shodan_search_output_textBrowser.setObjectName("shodan_search_output_textBrowser")
        self.horizontalLayout_3.addWidget(self.shodan_search_output_textBrowser)
        self.gridLayout.addWidget(self.shodan_groupBox, 3, 0, 1, 1)
        self.censys_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.censys_groupBox.setObjectName("censys_groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.censys_groupBox)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.censys_search_output_textBrowser = QtWidgets.QTextBrowser(self.censys_groupBox)
        self.censys_search_output_textBrowser.setMinimumSize(QtCore.QSize(167, 158))
        self.censys_search_output_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.censys_search_output_textBrowser.setStyleSheet("background-color: paleteGreen;\n"
"border-radius:15px")
        self.censys_search_output_textBrowser.setOpenExternalLinks(True)
        self.censys_search_output_textBrowser.setObjectName("censys_search_output_textBrowser")
        self.horizontalLayout_5.addWidget(self.censys_search_output_textBrowser)
        self.gridLayout.addWidget(self.censys_groupBox, 3, 1, 1, 1)
        self.binaryedge_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.binaryedge_groupBox.setObjectName("binaryedge_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.binaryedge_groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.binaryedge_search_output_textBrowser = QtWidgets.QTextBrowser(self.binaryedge_groupBox)
        self.binaryedge_search_output_textBrowser.setMinimumSize(QtCore.QSize(190, 158))
        self.binaryedge_search_output_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.binaryedge_search_output_textBrowser.setStyleSheet("background-color: paleteGreen;\n"
"border-radius:15px")
        self.binaryedge_search_output_textBrowser.setOpenExternalLinks(True)
        self.binaryedge_search_output_textBrowser.setObjectName("binaryedge_search_output_textBrowser")
        self.verticalLayout_2.addWidget(self.binaryedge_search_output_textBrowser)
        self.gridLayout.addWidget(self.binaryedge_groupBox, 3, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        allsearch.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(allsearch)
        self.statusbar.setObjectName("statusbar")
        allsearch.setStatusBar(self.statusbar)
        self.actionsss = QtWidgets.QAction(allsearch)
        self.actionsss.setMenuRole(QtWidgets.QAction.AboutRole)
        self.actionsss.setObjectName("actionsss")
        self.actionhelp = QtWidgets.QAction(allsearch)
        self.actionhelp.setObjectName("actionhelp")

        self.retranslateUi(allsearch)
        QtCore.QMetaObject.connectSlotsByName(allsearch)

    def retranslateUi(self, allsearch):
        _translate = QtCore.QCoreApplication.translate
        allsearch.setWindowTitle(_translate("allsearch", "Search Tools V1.5.2"))
        self.start_search_pushButton.setText(_translate("allsearch", "开始搜索"))
        self.start_keywords_lineEdit.setPlaceholderText(_translate("allsearch", "ip=10.20.30.1|ips=10.20.30.1/24"))
        self.proxy_checkBox.setText(_translate("allsearch", "代理"))
        self.start_time_spinBox.setSuffix(_translate("allsearch", "天"))
        self.proxy_test_pushButton.setText(_translate("allsearch", "验证代理"))
        self.notice_groupBox.setTitle(_translate("allsearch", "提示信息：↓"))
        self.label.setText(_translate("allsearch", "代理信息：↓"))
        self.proxy_output_textBrowser.setHtml(_translate("allsearch", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'&quot;华文细黑&quot;\'; font-size:14pt;\"><br /></p></body></html>"))
        self.count_label.setText(_translate("allsearch", "统计信息：↓"))
        self.final_result_groupBox.setTitle(_translate("allsearch", "Final Result："))
        self.fofa_groupBox.setTitle(_translate("allsearch", "Fofa："))
        self.zoomeye_groupBox.setTitle(_translate("allsearch", "Zoomeye："))
        self.quake_groupBox.setTitle(_translate("allsearch", "Quake："))
        self.shodan_groupBox.setTitle(_translate("allsearch", "Shodan："))
        self.shodan_search_output_textBrowser.setHtml(_translate("allsearch", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.censys_groupBox.setTitle(_translate("allsearch", "Censys："))
        self.binaryedge_groupBox.setTitle(_translate("allsearch", "Binaryedge："))
        self.actionsss.setText(_translate("allsearch", "sss"))
        self.actionhelp.setText(_translate("allsearch", "help"))
